version: '3'
services:
  ui:
    container_name: ui
    build: ./ui
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      - api
  api:
    container_name: service
    build: ./api
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - db
  db:
    image: postgres:13.1
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Acaba1234!**
      - APP_DB_USER=admin
      - APP_DB_PASS=Acaba1234!**
      - APP_DB_NAME=todo
    ports:
      - 5435:5432