name: Api-Pipeline

on:
  push:
    paths:
      - "**"
      - "!ui/**"
      - "!.github/workflows/ui-pipeline.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        working-directory: ./api
        run: go build

      - name: Test
        working-directory: ./api/domain/repository
        run: go test

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker build & push
        working-directory: ./api
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build -t barisakdas/golang-todo-api:v${{ github.run_number }} .
          docker push barisakdas/golang-todo-api:v${{ github.run_number }}
          