name: Ui-Pipeline

on:
  push:
    paths:
      - "**"
      - "!api/**"
      - "!.github/workflows/api-pipeline.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Npm
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Npm install
        working-directory: ./ui
        run: npm install

      - name: Build
        working-directory: ./ui
        run: yarn build

      - name: Test
        working-directory: ./ui
        run: npm test

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker build & push
        working-directory: ./ui
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build -t barisakdas/react-todo-ui:v${{ github.run_number }} .
          docker push barisakdas/react-todo-ui:v${{ github.run_number }}