name: Ui-Pipeline

on:
  push:
    paths:
      - "**"
      - "!api/**"
      - "!.github/workflows/api-pipeline.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Npm
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Npm install
        working-directory: ./ui
        run: npm install

      - name: Build
        working-directory: ./ui
        run: yarn build

      - name: Test
        working-directory: ./ui
        run: npm test

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker build & push
        working-directory: ./ui
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build -t barisakdas/react-todo-ui:v${{ github.run_number }} .
          docker push barisakdas/react-todo-ui:v${{ github.run_number }}

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: cluster-1
          location: europe-west1-b
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Helm Update
        working-directory: ./helm/ui/todo-app-ui
        run: helm upgrade todo-app-ui --install -f values.yaml --set image.tag="v${{ github.run_number }}" --namespace todo-app  .
